# Generated by Django 4.2 on 2026-01-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_liveboard_team_alter_player_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Live Team Selection Board', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSelectionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['team__name', 'slot_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='slot',
            name='board',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='player',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='team',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='LiveBoard',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.AddField(
            model_name='teamselectionslot',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player'),
        ),
        migrations.AddField(
            model_name='teamselectionslot',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.teamselection'),
        ),
        migrations.AddField(
            model_name='teamselectionslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamselectionslot',
            unique_together={('selection', 'team', 'slot_number')},
        ),
    ]
