# Generated by Django 4.2 on 2026-01-23 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teamselection_teamselectionslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pref_pos1',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1st preferred position number (1-23)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='player',
            name='pref_pos2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='2nd preferred position number (1-23)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='player',
            name='pref_pos3',
            field=models.PositiveSmallIntegerField(blank=True, help_text='3rd preferred position number (1-23)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
